### ISSUE TITLE
SASS에서 부모 selector를 변수에 담아 자식 selector 에서 활용하는 법

### ISSUE THREAD

**Issue by delivan** [delivan/til-archive#15]
```html
<div class='example small'>
    <span class='example__value'>small</span>
</div>
<div class='example big'>
    <span class='example__value'>big</span>
</div>
```
```scss
.example {
    $root: &;

    &.small {
	width: 20px;
	#{$root} {
		&__value {
			font-size: 16px;
		}
	}
    }
    &.big {
        width: 40px;
	#{$root} {
		&__value {
			font-size: 32px;
		}
	}
}
```
