### ISSUE TITLE
li 태그 스타일 커스터마이징

### ISSUE THREAD

**Issue by delivan** [delivan/til-archive#3]
```css
ul {
  margin: 0;
}
ul.dashed {
  list-style-type: none;
}
ul.dashed > li {
  text-indent: -1rem;
}
ul.dashed > li:before {
  content: " - ";
}
```
