### ISSUE TITLE
CSS로 대각선을 구현하고 싶을 때 사용할 수 있는 방법들

### ISSUE THREAD

**Issue by delivan** [delivan/til-archive#6]
```css
// 직관적이고 사용하기 쉬우나 대각선 부분이 약간 깨지는 것이 흠
.diagonal {
  background: line-gradient(20deg, black 50% white 50%);
}
```
```css
// 대각선 부분이 깨지지 않음. 해당 엘리먼트의 양옆, 위아래를 잡아당기는 느낌
.diagonal {
  transform: skew(20deg);
}
```
