### ISSUE TITLE
HTML5 data-* 속성

### ISSUE THREAD

**Issue by delivan** [delivan/til-archive#9]
HTML5의 `data-*` 속성으로 화면에 보이지 않게 데이터들을 담아둘 수 있다.
이 데이터를 읽으러면 `element.getAttribute(attributeName)` 을 사용할 수도 있지만 더 쉽게 `event.target.dataset`으로 읽을 수 있다(IE11부터 가능). 읽어올 때 대쉬(-) 는 camelCase로 변환되며, 각 데이터들은 모두 string으로 변환되므로 읽어온 뒤 변환시킬 필요도 있다.
 
```jsx
// on React Component
const onClickLabelHandler = e => {
  const name = e.target.dataset.name;
  const isChecked =  e.target.dataset.isChecked === 'true' ? true : false;
  ...
};

...
<Label
  data-name={data.name}
  data-is-checked={data.isChecked}
  onClick={onClickLabelHandler}
>
...
```

HTML 속성이므로 CSS에서도 읽어올 수 있으며 속성 선택자로 활용가능하다.
```css
label::before {
  content: attr(data-name);
}

label[data-is-checked='true'] {
  color: green;
}
```
